---
global:
  pattern: rag-llm-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
# Possible value for db.type = [REDIS, EDB]
  db:
    index: docs
    type: EDB
# Add for model ID
  model:
      modelId: mistral-community/Mistral-7B-Instruct-v0.3
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
