apiVersion: batch/v1
kind: Job
metadata:
  name: create-ds-connections
spec:
  selector: {}
  template:
    spec:
      containers:
        - args:
            - -ec
            - |-
              echo -n 'Waiting for openshift ai initialize'
              while ! oc describe sub rhods-operator -n redhat-ods-operator 2>/dev/null | grep -qF rhods-operator; do
                echo -n .
                sleep 5
              done; echo
              oc patch installplan install-nlbqq --namespace redhat-ods-operator --type merge --patch '{"spec":{"approved":true}}'
              sleep 10

              cat << EOF | oc apply -f-
              apiVersion: datasciencecluster.opendatahub.io/v1
              kind: DataScienceCluster
              metadata:
                labels:
                  app.kubernetes.io/created-by: rhods-operator
                  app.kubernetes.io/instance: default-dsc
                  app.kubernetes.io/managed-by: kustomize
                  app.kubernetes.io/name: datasciencecluster
                  app.kubernetes.io/part-of: rhods-operator
                name: default-dsc
              spec:
                components:
                  codeflare:
                    managementState: Removed
                  kserve:
                    managementState: Managed
                    serving:
                      ingressGateway:
                        certificate:
                          type: SelfSigned
                      managementState: Managed
                      name: knative-serving
                  trustyai:
                    managementState: Removed
                  ray:
                    managementState: Removed
                  kueue:
                    managementState: Removed
                  workbenches:
                    managementState: Managed
                  dashboard:
                    managementState: Managed
                  modelmeshserving:
                    managementState: Managed
                  datasciencepipelines:
                    managementState: Managed
              EOF
          command:
            - /bin/bash
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          name: create-ds-connections
      restartPolicy: Never
      serviceAccount: demo-setup
      serviceAccountName: demo-setup