apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: rag-llm
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  dataFrom:
  - extract:
      key: {{ .Values.minio.key }}