apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: frontend
  name: ai-llm-gradio-sm
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - tgis-llm-demo
  selector:
    matchExpressions:
      - {key: app.kubernetes.io/name, operator: In, values: [rag-llm]}
