llm_providers:
  - name: "OpenShift AI (vLLM)"
    enabled: True
    models:
      - name: "{{ (lookup "v1" "Secret" .Release.Namespace "huggingface-secret").data.modelId | b64dec | quote }}"
        weight: 1
        enabled: True
        url: https://{{ (lookup "v1" "Secret" .Release.Namespace "huggingface-secret").data.modelId | b64dec | quote }}-{{ .Values.llmui.namespace }}.{{ coalesce .Values.global.localClusterDomain .Values.global.hubClusterDomain }}/v1
        params:
          - name: max_new_tokens
            value: 1024
          - name: temperature
            value: 0.01
          - name: top_k
            value: 10
          - name: top_p
            value: 0.95
          - name: repetition_penalty
            value: 1.03
          - name: verbose
            value: False
          - name: typical_p
            value: 0.95
default_provider: "OpenShift AI (vLLM)"
default_model: "{{ (lookup "v1" "Secret" .Release.Namespace "huggingface-secret").data.modelId | b64dec | quote }}"
# type values=(default, round_robin,  all)
type: all