apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mistral-7b-instruct-v02
  generation: 1
  namespace: tenant-ns
  finalizers:
    - inferenceservice.finalizers
  labels:
    networking.knative.dev/visibility: cluster-local
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '8'
          memory: 10Gi
        requests:
          cpu: '4'
          memory: 8Gi
      runtime: mistral-7b-instruct-v02
      storage:
        key: aws-connection-test-bucket
        path: models
